START TRANSACTION;

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS device_status_logs;
DROP TABLE IF EXISTS temperature_logs;
DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS rooms;

SET FOREIGN_KEY_CHECKS = 1;

COMMIT; 